apiVersion: datasciencecluster.opendatahub.io/v1alpha1
kind: DataScienceCluster
metadata:
  name: default
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opendatahub-operator
spec:
  components:
    codeflare:
      enabled: true
    dashboard:
      enabled: true
    datasciencepipelines:
      enabled: true
    kserve:
      enabled: true
    modelmeshserving:
      enabled: true
    ray:
      enabled: true
    workbenches:
      enabled: true