apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-core
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/operator
    name: prometheus-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-notebook-controller
    name: odh-notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: notebook-images
    name: notebook-images
  - kustomizeConfig:
      parameters:
      - name: monitoring-namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: model-mesh
    name: model-mesh
  - kustomizeConfig:
      parameters:
      - name: deployment-namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: modelmesh-monitoring
    name: modelmesh-monitoring
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: data-science-pipelines-operator/
    name: data-science-pipelines-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: trustyai-service-operator
    name: trustyai-service-operator
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
  version: master