
appName: inferencing-app
namespace: inferencing-app
uri: https://github.com/arslankhanali/credit-fraud-detection-demo
contextDir: application
originalimage: python:3.10.4
inferenceEndpoint: http://modelmesh-serving.credit-fraud-model:8008/v2/models/credit-card-fraud/infer
port: 8080
protocol: TCP